[meta]
title = "demo"
description = "xxx的个人网站，记录生活、技术、随笔等等。"
author = "Albert"
keywords = "个人博客 xxxx 静态站点"
locale = "zh_CN"
lang = "zh-CN"
siteUrl = "xxxxxx"
theme-color = "#8a5cf5"
icpNumber = ""
themeLink = ""

[homepage]
title = "Albert's Blog"
description = "能纵棹，惯乘流，长江白浪不曾忧"

[page]
pageSize = 10

[datetime]
frontmatterFields = ["date", "created", "createdAt", "published", "publishedAt"]
formats = ["YYYY-MM-DD", "YYYY/MM/DD", "YYYY-MM-DD HH:mm:ss", "YYYY/MM/DD HH:mm:ss", "YYYY-MM-DDTHH:mm:ssZ"]
outputFormat = "YYYY/MM/DD"

[blog]
defaultViewMode = "card"

[outline]
title = "Table of Contents"

[timeline]
sortDirection = "desc"

[links]
resolutionModes = ["repoRoot", "absolutePath", "relativeToCurrentFile", "obsidianShortest"]

[nav]
home = "Home"
tags = "Tags"
timeline = "Timeline"
pages = "Pages"
about = "About"

[markdown]
mathjax = true
wikilinks = true
footnote = true
hashtag = true
mermaid = true
mermaid_render = "svg"
callout = true
render_title = "frontmatter_title"
link_style = "wiki"

[theme]
vp-c-bg = "#ffffff"
vp-c-bg-alt = "#f6f6f6"
vp-c-brand = "#9873f7"
vp-c-brand-1 = "#8a5cf5"
vp-c-brand-2 = "#a68af9"
vp-c-text-1 = "#222222"
vp-c-text-2 = "#5c5c5c"
vp-c-divider = "#e0e0e0"
vp-button-brand-bg = "#9873f7"
vp-code-bg = "#f6f6f6"
vp-code-block-bg = "#f6f6f6"
vp-sidebar-bg-color = "#f6f6f6"
c-text-code = "#e93147"
c-text-strong = "#111111"
c-text-em = "#086ddd"

[theme.dark]
vp-c-bg = "#1e1e1e"
vp-c-bg-alt = "#262626"
vp-c-brand = "#8a5cf5"
vp-c-brand-1 = "#a68af9"
vp-c-brand-2 = "#c5b6fc"
vp-c-text-1 = "#dadada"
vp-c-text-2 = "#b3b3b3"
vp-c-divider = "#363636"
vp-button-brand-bg = "#8a5cf5"
vp-code-bg = "#262626"
vp-code-block-bg = "#262626"
vp-sidebar-bg-color = "#242424"
c-text-code = "#fb464c"
c-text-strong = "#ebebeb"
c-text-em = "#027aff"
