[meta]
title = "demo"
description = "xxx的个人网站，记录生活、技术、随笔等等。"
author = "xxxxx"
keywords = "个人博客 xxxx 静态站点"
locale = "zh_CN"
lang = "zh-CN"
siteUrl = "xxxxxx"
theme-color = "#42b983"

[page]
pageSize = 10

[theme]
vp-c-brand = "#42b983"
c-text-code = "#00ff00"
c-text-strong = "#ff0000"
c-text-em = "#0000ff"
tag-info = "#42b983"
tag-count = "#42b983"
tag-hover = "#42b983"

[theme.dark]
vp-c-bg = "#020405"
c-text-code = "#00ff00"
c-text-strong = "#ff0000"
c-text-em = "#00ffff"
vp-c-brand = "#42b983"
tag-info = "#42b983"
tag-count = "#42b983"
tag-hover = "#42b983"
