[meta]
title = "demo"
description = "xxx的个人网站，记录生活、技术、随笔等等。"
author = "xxxxx"
keywords = "个人博客 xxxx 静态站点"
locale = "zh_CN"
lang = "zh-CN"
siteUrl = "xxxxxx"
theme-color = "#42b983"

[page]
pageSize = 10

[theme]
brandColor = "#42b983"
